modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/FireMuffin303/Muffin-s-Picnic/issues"
license = "MIT License"

[[mods]]
modId = "muffins_picnic"
version = "${version}"
displayName = "Muffin's Picnic"
authors = "FireMuffin303!"
description = '''
Add Picnic Basket to carry items and hangout!
'''
logoFile = "icon.png"

[[dependencies.muffins_picnic]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_picnic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
